name: kasir_pro
description: "KasirPro - A point of sale (POS) app for small businesses."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.1.0
  http: ^1.1.0
  encrypt: ^5.0.1
  crypto: ^3.0.3
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  provider: ^6.1.1


  # ðŸ”¥ Firebase dependencies
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  firebase_messaging: ^15.1.3
  google_sign_in: ^6.2.1
  email_auth: ^1.1.0 # untuk OTP verifikasi via email
  flutter_dotenv: ^6.0.0
  emailjs: ^1.1.1
  intl: ^0.20.2
  image_picker: ^1.0.7
  pdf: ^3.10.4
  printing: ^5.9.1
  fl_chart: ^0.68.0

  flutter_localizations:
    sdk: flutter
  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/google_logo.png
    - assets/login_illustration.png
    - assets/qris_dummy.png
    - .env
